version: "3.7"

services:
  database: #ESSE É O NOME DO SERVICE QUE DEVE ESTAR NO ARQUIVO DE CRIAÇÃO DE CONEXÃO
    image: postgres
    container_name: database_ignite
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=lebkkwcevdgwef
      - POSTGRES_PASSWORD=1d1de91a795d6cb130d74915d374abd31fc19952bf775db5ead6945adc9e2fea
      - POSTGRES_NAME=d7e33mqg5ottr8
  app:
    build: .
    container_name: rentx
    restart: always
    command: sh -c "npm run migrate run && npm run start"
    ports: 
      - 3000:3000
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database
    evironment: 
      DB_HOST: ec2-54-211-255-161.compute-1.amazonaws.com
      DB_USER: lebkkwcevdgwef
      DB_PASS: 1d1de91a795d6cb130d74915d374abd31fc19952bf775db5ead6945adc9e2fea
      DB_NAME: d7e33mqg5ottr8
volumes:
  pgdata:
    driver: local